### PR TITLE
Update regex name parsing

### PR DESCRIPTION
**Pull request by jaap**

### CODE REVIEW

**Comment by jaap** [comment]
@ricbra it seems, however, that the @group integration is not runned on Travis? (Sorry, lack of PHPunit experience here...). Running it as 'phpunit --group integration' will pass though.

**Comment by jaap** [comment]
Found out what you we're doing with the local data, so added that as well.

**Comment by jaap** [comment]
@ricbra did you have a look at my PR's? Is there anything you'd like to be adjusted? Would be nice to implement your package again instead of my fork ;)

**Comment by ricbra** [comment]
Been away a couple of days, will try to take a look asap.... sorry for the delay 😄

**Comment by jaap** [comment]
Any news :)

**Comment by ricbra** [comment]
Haven't been touching my PC too much during vacation time. Thank you for your patience 😄 .

Added a couple of small comments, would be nice if you could fix those and then we're good to go!

**Comment by jaap** [comment]
changes addressed in #5

**Pull request closed without merging**
